### ISSUE TITLE
[RESPONSIVE DESIGN - ANDROID] Broken link to Use Agreement

### ISSUE THREAD

**Issue by gocadimic** [OpenMobileAlliance/oma-knowledge-base#360] opened 2024-11-05 17:07 UTC
URL:** https://openmobilealliance.org/omaspecworks/collaborate/affiliates/wireless-village
     **Device Type:** Android v14
     **Issue Description:**The Use Agreement link is broken
     **Steps to Reproduce:**
       1. Open the URL on Android v14.
       2. Scroll over the page
       3. Click to open Use Agreement
       4. Actual: The link seems to present 404
        **Screenshots:** 
![Screenshot_20241105_175732_Chrome](https://github.com/user-attachments/assets/0c6c1eee-d57e-4a81-b04e-e02f7f2d5789)

**Comment by FroudeDescartes** [comment] 2024-11-06 16:40
I was not able to reproduce results neither on Android nor on PC

**Comment by FroudeDescartes** [comment] 2024-11-06 16:44
Closing it for the time

**Comment by gocadimic** [comment] 2024-11-06 22:33
The link under 'Click here to view Use Agreement' was broken.

**Comment by gocadimic** [comment] 2024-11-06 22:36
Resolved in PR #371

**Closed** 2024-11-06 22:36 UTC
Labels: P1
